// ─────────────────────────────────────────────────────────────────
// Placeholder data for subjects that do not yet ship real generated data.
// Each block assigns to its registered `dataVar` and uses
// `makePlaceholderData` to keep the shape identical to OH_SITE_DATA.
// To replace with real content: keep the same shape; you can either
// (a) keep using makePlaceholderData with richer chapter defs, or
// (b) assign a hand-crafted object identical in shape to OH_SITE_DATA.
// ─────────────────────────────────────────────────────────────────

(function () {
  // 毒理学 (toxicology) now ships real data via tox-data.js
  // (window.TOX_SITE_DATA, generated by build-data.js) — no placeholder here.
  // 环境健康学 (environmental-health) now ships real data via env-data.js
  // (window.ENV_SITE_DATA, generated by build-data.js) — no placeholder here.

  // 流行病学 (epidemiology) now ships real data via epi-data.js
  // (window.EPI_SITE_DATA, generated by build-data.js) — no placeholder here.
  // 营养与食品卫生学 (nutrition-food-hygiene) now ships real data via nutr-data.js
  // (window.NUTR_SITE_DATA, generated by build-data.js) — no placeholder here.
  // 精神病学 (psychiatry) now ships real data via psy-data.js
  // (window.PSY_SITE_DATA, generated by build-data.js) — no placeholder here.
  // 职业病学 (occupational-disease) now ships real data via od-data.js
  // (window.OD_SITE_DATA, generated by build-data.js) — no placeholder here.
})();
