// ─────────────────────────────────────────────────────────────────
// Placeholder data for subjects that do not yet ship real generated data.
// Each block assigns to its registered `dataVar` and uses
// `makePlaceholderData` to keep the shape identical to OH_SITE_DATA.
// To replace with real content: keep the same shape; you can either
// (a) keep using makePlaceholderData with richer chapter defs, or
// (b) assign a hand-crafted object identical in shape to OH_SITE_DATA.
// ─────────────────────────────────────────────────────────────────

(function () {
  const R = window.SUBJECTS_REGISTRY;
  const find = (slug) => R.find(s => s.slug === slug);
  const build = window.makePlaceholderData;

  // 毒理学 (toxicology) now ships real data via tox-data.js
  // (window.TOX_SITE_DATA, generated by build-data.js) — no placeholder here.
  // 环境健康学 (environmental-health) now ships real data via env-data.js
  // (window.ENV_SITE_DATA, generated by build-data.js) — no placeholder here.

  // 流行病学 (epidemiology) now ships real data via epi-data.js
  // (window.EPI_SITE_DATA, generated by build-data.js) — no placeholder here.

  window.NUTR_SITE_DATA = build(find('nutrition-food-hygiene'), [
    { title: '营养学基础', points: [
      { title: '能量代谢与膳食能量推荐摄入量', freq: 1 },
      { title: '宏量营养素：蛋白质 / 脂类 / 碳水化合物', freq: 2 },
    ]},
    { title: '维生素与矿物质', points: [
      { title: '脂溶性 vs 水溶性维生素', freq: 1 },
      { title: '常见矿物质的生理功能与缺乏症', freq: 1 },
    ]},
    { title: '特殊人群营养', points: [
      { title: '孕妇与乳母营养', freq: 1 },
      { title: '婴幼儿、老年人营养', freq: 1 },
    ]},
    { title: '公共营养', points: [
      { title: '膳食指南与平衡膳食宝塔', freq: 1 },
    ]},
    { title: '食品卫生学', points: [
      { title: '食品的细菌污染与腐败变质', freq: 2 },
      { title: '食物中毒：细菌性 / 化学性 / 有毒动植物', freq: 1 },
    ]},
    { title: '食品安全管理', points: [
      { title: 'HACCP 体系与食品安全监管', freq: 1 },
    ]},
  ]);

  window.PSY_SITE_DATA = build(find('psychiatry'), [
    { title: '精神病学绪论', points: [
      { title: '精神障碍的概念与分类', freq: 1 },
    ]},
    { title: '精神症状学', points: [
      { title: '感知障碍：幻觉与错觉', freq: 1 },
      { title: '思维障碍：妄想与思维形式障碍', freq: 2 },
      { title: '情感与意志行为障碍', freq: 1 },
    ]},
    { title: '心境障碍', points: [
      { title: '抑郁障碍：诊断与治疗要点', freq: 2 },
      { title: '双相情感障碍', freq: 1 },
    ]},
    { title: '焦虑及相关障碍', points: [
      { title: '广泛性焦虑 / 惊恐障碍', freq: 1 },
    ]},
    { title: '精神分裂症', points: [
      { title: '阳性 / 阴性症状', freq: 1 },
      { title: '抗精神病药物的分类', freq: 1 },
    ]},
    { title: '器质性精神障碍', points: [
      { title: '谵妄与痴呆', freq: 1 },
    ]},
  ]);

  window.OD_SITE_DATA = build(find('occupational-disease'), [
    { title: '职业病学概论', points: [
      { title: '职业病的定义与法定职业病分类', freq: 2 },
      { title: '职业病诊断与鉴定程序', freq: 1 },
    ]},
    { title: '尘肺', points: [
      { title: '矽肺的发病机制与临床分期', freq: 2 },
      { title: '煤工尘肺与石棉肺', freq: 1 },
    ]},
    { title: '职业中毒', points: [
      { title: '铅、汞、镉慢性中毒的临床特征', freq: 2 },
      { title: '有机磷农药急性中毒处理', freq: 1 },
    ]},
    { title: '物理因素职业病', points: [
      { title: '噪声聋 / 手臂振动病 / 中暑', freq: 1 },
    ]},
    { title: '职业性肿瘤与皮肤病', points: [
      { title: '常见职业性致癌物与靶器官', freq: 1 },
    ]},
    { title: '职业病三级预防', points: [
      { title: '工程控制、个人防护与健康监护', freq: 1 },
    ]},
  ]);
})();
